# Generated by Django 4.2.1 on 2023-06-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_director_photo_url_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.actor'),
        ),
    ]
