# Generated by Django 4.2.1 on 2023-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_director_description_movie_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, to='films.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, to='films.director'),
        ),
    ]
