# Generated by Django 4.2.1 on 2023-06-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_movie_actor_remove_movie_director_movie_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
